version: '2'
services:
  frontend:
    extends:
      file: common.yml
      service: frontend
    links:
      - backend
    volumes:
      - ../src/client/public:/app/public
  backend:
    extends:
      file: common.yml
      service: backend
    links:
      - db
    environment:
      - DATABASE_URL=mongodb://db/kalico_db
    volumes:
      - ../src/server:/server
    command: node_modules/.bin/nodemon server.js
  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - ../volumes/mongodb:/data/db
