version: '2'
services:
  frontend:
    extends:
      file: common.yml
      service: frontend
    restart: always
  backend:
    extends:
      file: common.yml
      service: backend
    restart: always
  db:
    extends:
      file: common.yml
      service: db
    restart: always
